### ISSUE TITLE
Document the package build process and make a release

### ISSUE THREAD

**Issue by frank-trampe** [fontforge/fontforge#1469]
Its important to know how the package generation process works and what improvements it might need before then so we can do a release.
## PACKAGING

SRC release @frank-trampe 
- [x]  providing bootstrapped tarball in next stable release (#1725)

DEB builds @frank-trampe 
- [x] top level Makefile update, so you can run `make deb-src` to make a Debian Rules file etc, #229, and make a tarball and use `dput` to push the source package to launchpad. https://github.com/fontforge/fontforge/issues/1339 seems like on the critical path for this.
- [x] Ask Debian maintainers to make a new DEP-5 file (https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/)
- [x] Ask Debian maintainers to ensure the `debian/copyright` file is up to date, and confirm this on http://lists.alioth.debian.org/pipermail/pkg-fonts-devel/2014-August/014800.html

RPM builds @frank-trampe 
- [x] source package builder shell script added to repo for making a RPM `spec` file ([docs](https://fedoraproject.org/wiki/How_to_create_an_RPM_package#Building_the_binary_package)) (maybe find help [here](https://build.opensuse.org/project/repositories/home:monkeyiq) or [here](https://build.opensuse.org/package/show/home:monkeyiq:fontforge/fontforge-git))
- [x] top level Makefile update, so you can run `make rpm-src` to get a srpm
- [x] RPM spec file needs updating to the latest binary package dependencies (following discussion in https://github.com/fontforge/fontforge/pull/1739)

OSX builds @monkeyiq 
- [x] Homebrew recipe updated
- [x] Homebrew recipe pull request sent, https://github.com/Homebrew/homebrew/pull/31500
- [x] Homebrew recipe pull request accepted
- [x] On BigV, use a directory mask like "year-month-date-PRnum-githash" and set up a cronjob shell script on bigv to rm anything older than 1 month
- [x] ~~Replace macports-based monkeyiq-macbook-air-built bundle daily builds uploaded to fuuko with homebrew-based and travis-built ones uploaded to bigv~~ (cancelled as travisCI is too puny)
- [x] Get homebrew-based App build working and installable with standard homebrew commands @monkeyiq - #1344
- [x] ~~Change "macbook-air-built, macports-based daily build to upload to fuuko" to "macbook-air-built homebrew-based daily build uploaded to bigv" by @monkeyiq - #1344~~ (cancelled as not important)

WIN builds @jtanx 
- [x] Windows binary of release

Misc
- [x] Ensure it builds with autoconf v2.69 so it has aarch64 support (as per https://github.com/fontforge/fontforge/commit/aba943acc7f129301760bb31ae59b4230c9e86a2#commitcomment-3054897)
## Documentation
- [ ] 'How to set up your own Fedora daily RPM' process documented [here](http://fontforge.github.io/en-US/documentation/developers/) @frank-trampe 
- [x] Make developer documentation on 'How to set up your own Ubuntu DEB build and PPA' [here](http://fontforge.github.io/en-US/documentation/developers/)
- [x] Make developer documentation on 'How to set up your own Fedora RPM build' [here](http://fontforge.github.io/en-US/documentation/developers/)
- [ ] Make developer documentation on 'How to set up your own Mac app' [here](http://fontforge.github.io/en-US/documentation/developers/) @frank-trampe 
- [ ] Win native build documented [here](http://fontforge.github.io/en-US/documentation/developers/) 
- [ ] Win cross compile build documented [here](http://fontforge.github.io/en-US/documentation/developers/) 
- [ ] Release process documented [here](https://github.com/fontforge/fontforge.github.io/blob/master/en-US/documentation/developers/release.md)

**Comment by bennettrogers** [comment]
I'm trying to build a Fontforge RPM on RHEL7. I'm using the steps documented [here](http://fontforge.github.io/en-US/documentation/developers/).

The build process seems to work fine. All RPMs end up where they should. But if I try to install any of them, I get dependency errors. For example, calling:

```yum localinstall fontforge-20150228-1.x86_64.rpm```

fails with:

```
Error: Package: fontforge-20150228-1.x86_64 (/fontforge-20150228-1.x86_64)
           Requires: libgioftp.so.2()(64bit)
Error: Package: fontforge-20150228-1.x86_64 (/fontforge-20150228-1.x86_64)
           Requires: libgdraw.so.5()(64bit)
Error: Package: libfontforge1-20150228-1.x86_64 (local)
           Requires: libgioftp.so.2()(64bit)
Error: Package: libfontforge1-20150228-1.x86_64 (local)
           Requires: libgunicode.so.4()(64bit)
Error: Package: libfontforge1-20150228-1.x86_64 (local)
           Requires: libgutils.so.2()(64bit)
Error: Package: fontforge-20150228-1.x86_64 (/fontforge-20150228-1.x86_64)
           Requires: libfontforge.so.2()(64bit)
Error: Package: libfontforge1-20150228-1.x86_64 (local)
           Requires: libgcc1
Error: Package: fontforge-20150228-1.x86_64 (/fontforge-20150228-1.x86_64)
           Requires: /usr/local/bin/fontforge
Error: Package: libgdraw4-20150228-1.x86_64 (local)
           Requires: libgcc1
Error: Package: libfontforge1-20150228-1.x86_64 (local)
           Requires: libfontforge.so.2()(64bit)
Error: Package: fontforge-20150228-1.x86_64 (/fontforge-20150228-1.x86_64)
           Requires: libgunicode.so.4()(64bit)
Error: Package: fontforge-20150228-1.x86_64 (/fontforge-20150228-1.x86_64)
           Requires: libfontforgeexe.so.2()(64bit)
Error: Package: libgdraw4-20150228-1.x86_64 (local)
           Requires: libgdraw.so.5()(64bit)
Error: Package: fontforge-20150228-1.x86_64 (/fontforge-20150228-1.x86_64)
           Requires: libgutils.so.2()(64bit)
Error: Package: libfontforge1-20150228-1.x86_64 (local)
           Requires: libfontforgeexe.so.2()(64bit)
```

Some of these packages are also created by the build process, and some are not. I've also tried putting all RPMs in a true yum repo, with the same results.

It's quite likely I'm doing something wrong, but should this build process work on RHEL7 or CentOS7?

**Comment by pnemade** [comment]
We don't install files under /usr/local/ directory and from above output, it looks the fontforge rpm created is not as per Fedora's packaging guidelines. If you just want to get latest updates to fontforge releases then add new yum repository https://copr.fedoraproject.org/coprs/pnemade/fontforge/repo/epel-7/pnemade-fontforge-epel-7.repo in /etc/yum.repos.d directory.

Then run as root user
yum clean all;yum update fontforge

**Comment by bennettrogers** [comment]
We'd like to be able to create our own RPMs with some code changes, which was why I was learning the documented build process for the upstream repo. If the RPM resulting from the documented process doesn't work because it doesn't follow packaging guidelines, could the specfile be updated so that it does work?

**Comment by bennettrogers** [comment]
Unfortunately the standard packages in the pnemade-fontforge repo don't seem to work, and neither do the RPMs available on the official GitHub releases page [here](https://github.com/fontforge/fontforge/releases/tag/20141014). Both versions give various dependency errors on RHEL7 (or CentOS7).

Is there anything I can do or any information I can provide to help debug these RPM installation issues?

Thanks!

**Comment by frank-trampe** [comment]
I will retest on CentOS soon (tomorrow, I expect).

**Comment by bennettrogers** [comment]
Excellent, please let me know what I can do to help!

**Comment by pnemade** [comment]
If you could have given the exact issue log here, I could have helped you quickly here. I will check on my RHEL7 VM and see if there is any issue then fix it

**Comment by pnemade** [comment]
@bennettrogers I just checked on my RHEL7 system and I can able to update fontforge package from existing fontforge-20120731b-12.el7.x86_64 to fontforge-20150228-1.el7.centos.x86_64 which is in the given repo. I even tested it by opening some random font and there is no crash.

**Comment by bennettrogers** [comment]
Attempting to install Fontforge 2015-02-28 from the pnemade-fontforge repo on a barebones RHEL7 AMI from EC2 (ami-4dbf9e7d) gives 2 dependency errors:

Error: Package: fontforge-20150228-1.el7.centos.x86_64 (pnemade-fontforge)
           Requires: autotrace
Error: Package: fontforge-20150228-1.el7.centos.x86_64 (pnemade-fontforge)
           Requires: libuninameslist.so.0()(64bit)

Where did you get those two dependencies installed from? Maybe they came with your older RPM that was already installed? There doesn't appear to be an autotrace package, and I don't see any install dependencies listed in the Fontforge install documentation (although I could be looking in the wrong place).

Installing from that repo using a barebones CentOS7 AMI (ami-c7d092f7) DOES work with no dependency issues. I think I already tried this, but I'm going to try following the RPM build/packaging instructions again on this CentOS7 instance to see if it works there since RHEL7 it doesn't work on RHEL7.

**Comment by bennettrogers** [comment]
Building the RPM from the 20150228 tag of this github repo still has dependency errors on installation under RHEL7 or CentOS7. The specfile generated via `make src-rpm` from the [github repo] (https://github.com/fontforge/fontforge/blob/master/Packaging/redhat/m4/rpm.spec) is vastly different from the one extracted from the source RPM in your [pnemade-fontforge repo] (http://pastebin.com/MxtznBXR). Now I'm thinking maybe I'm following the wrong documentation for building an RPM. What is the source of truth for the source and specfile for building the official RPMs? [This] (http://fontforge.github.io/en-US/documentation/developers/) doesn't seem to be it.

Thanks!

**Comment by bennettrogers** [comment]
Hello - checking in on this again (please let me know if I should reply on a different issue or open a new one instead of continuing to reply here). I gave up on this for a while, but have since tried the more recent releases and am still running into the same issues from above. It also seems like some of the documentation that I referenced above has been removed or is in the process of being replaced.

I believe I am following the prescribed build process (exactly as described [here](https://github.com/fontforge/fontforge/pull/1739#issuecomment-56200709) in #1739), and am running into dependency errors when installing the resulting RPM via yum. This is on a completely fresh RHEL7 instance, then installing the dependencies listed in that issue, running bootstrap, configure, and make rpm-src, then calling rpmbuild as specified.

@pnemade: You mention that you successfully upgraded your fontforge installation on a RHEL7 instance, but it's not clear if you built a new copy of the RPM or if you used a pre-built one. If you were able to successfully build and install a fresh RPM, would you mind sharing the steps you used? From what I can tell, it seems like there may be something missing from the build docs describing how to make the RPM. Also, you ask for the issue log - I'd be happy to provide that - do you mean the error output when installing the RPM?

Any help with this would be very much appreciated. If someone would like a clean RHEL7 EC2 image to test on I can probably provide that. It may just be a documentation issue, in which case it would be great to get that updated. Thanks!

**Comment by frank-trampe** [comment]
@bennettrogers, which spec file are you using?

And could you tell me which dependencies are missing?

**Comment by bennettrogers** [comment]
[This](https://github.com/fontforge/fontforge/releases/download/20150612/fontforge-20150612.spec) specfile from the release last week. Which is also the one generated by the ```make rpm-src``` command.

The dependency errors are the same as the ones I listed on March 17 in [this](https://github.com/fontforge/fontforge/issues/1469#issuecomment-82585103) comment.

**Comment by pnemade** [comment]
@bennettrogers the only I will say here is that I have [this repository] (https://copr.fedoraproject.org/coprs/pnemade/fontforge/repo/epel-7/pnemade-fontforge-epel-7.repo) which worked fine on RHEL7 installation, I even can use the recent fontforge release without issue (though not tested heavily on RHEL7).

**Comment by pnemade** [comment]
The recent srpm worked for me is available [here for download] (https://copr-be.cloud.fedoraproject.org/results/pnemade/fontforge/epel-7-x86_64/fontforge-20150612-1.fc23/fontforge-20150612-1.el7.centos.src.rpm)

**Comment by bennettrogers** [comment]
@pnemade Thanks, although I still have the same questions and issues that I did last time you suggested using that repo. What is the source of truth for the fontforge specfile? The one in the SRPM you're linking to is vastly different from the one in the [main repo](https://github.com/fontforge/fontforge/releases/download/20150612/fontforge-20150612.spec). How did you generate yours, and why is it so different?  Also, what is the correct process for building the RPM/SRPM (or at least, what is the process you are following)?

**Comment by pnemade** [comment]
I have not looked into upstream spec file as they generally write it too generic. They do not follow frequently changing Fedora packaging guidelines. Few things about my work I will add here.
1) If I am using Fedora then I will definitely use Fedora's packaging guidelines while generating any package srpm/rpms. The Fedora project recommends to follow their own packaging guidelines to create new package/rpms.
2) The spec file may vary among different RPM based distributions as every distribution carries their own macros, scripts while generating binary rpms.
3) I will generally not follow what upstream projects provide as SPEC file if I see its generic spec file. I will write my own spec file according to the distribution on which I will use it.

So for Fedora, I use https://fedoraproject.org/wiki/Packaging:Guidelines for creating fontforge package.

**Comment by skef** [comment]
This was mostly done and is now almost entirely superseded. Closing.
