### ISSUE TITLE
New layers palette

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#179]
- [ ] In https://github.com/fontforge/fontforge/pull/71 @khaledhosny said 'the new layers palette seems has its share of small annoyances (the + - buttons often just disappear, does not always grow to show all the layers, other stuff that I don’t recall right now).' The layers palette should be worked on so that all these things are robust :)
- [ ] Make anchors on their own layer, https://github.com/fontforge/fontforge/issues/711
- [ ] Allow spiro and bezier curves on the same glyph layer at the same time #858 
- [ ] A new layers palette should show the stacking order of elements
- [ ] Add a new column of checkboxes on the layers palette, 'Preview,' so the fill can toggled on a per-layer basis, as currently it is 'dumb' and only works for the current layer
- [ ] Change guide line-from-ruler point type from curve to corner (https://github.com/fontforge/fontforge/issues/672)
- [x] <strike>Allow dragging straight line splines on guide layers directly from any layer</strike> Bad idea
- [ ] Allow right clicking any guide directly from any layer, and having the menu show first a delete option (which means (1) select the spline (2) `Edit, Chop` it) then a seperator, then a list of all the layers, with a tick shown to the left of the layer it is on
- [ ] In the CV layers palette, rename 'Guide' to 'Global Guides' and show a 'G' for its type instead of '#'
- [ ] In the CV layers palette, allow the user to rename the 'Global Guides' label
- [ ] Add a new default background layer, shown between Guide and Back today, named 'Local Guides.' 
- [ ] Show the 'Global Guides' layer in the `Font Info, Layers` table, with layer type 'Global Guide'
- [ ] Allow placing images (File, Import) on the Guide layer by cut and paste. Current Import places images on the Back layer and won't allow them to be cut, switch to Guide layer, and paste them in the guide layer; instead they are pasted in to the Back layer again, even though that layer isn't active.
- [ ] Allow changing a layer to the 'Global Grid' type in the right click menu shown for cells in the 'Type' col, so there can be several Global Grids
- [ ] snap to guide intersections (https://github.com/fontforge/fontforge/issues/509)
- [ ] Add a new layer type 'Global Grid', adding 2 cols to the table in Font Info, labeled "X grid" and "Y Grid", with int values, for the units to the next x and y grid line distance (which will look similar to (and perhaps reuse code from) `View, Grid Fit, Show Grid Fit`) (https://github.com/fontforge/fontforge/issues/339)
- [ ] snap to grid intersections
- [ ] Add a 'lock' col to the layers palette for each layer (all types) that prevents edits to that layer when the lock attribute is turned on. 
- [ ] Add a new special layer named 'Anchors' which renders the anchor points, which are technically (in SFD/UFO/OTF/etc) stored in the Fore layer, but aren't needed to be seen all the time (https://github.com/fontforge/fontforge/issues/711)
- [ ] Add a new special layer named 'Components' which renders the components, which are technically (in SFD/UFO/OTF/etc) stored in the Fore layer, but aren't needed to be seen all the time. 
- [ ] Add a new special layer named 'Diacritic Cloud' which renders all the components and marks associated with the base glyph, like Glyphs does this:

![dia-9](https://cloud.githubusercontent.com/assets/261579/4799698/b7a0ac8e-5e1e-11e4-9b56-01d55eba78bc.PNG)

**Comment by davelab6** [comment]
@andreaslarsen :)

**Comment by adrientetar** [comment]
Also Mse toolbar has been broken for me so far (#1456).
