### ISSUE TITLE
2014-12 Release

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#1805]
(Moving all this stuff from previous release issue)

https://github.com/fontforge/fontforge/wiki/Making-a-release describes the process for making a release

Ubuntu
- [x] @frank-trampe said, "There is not a common libtiff version available both on precise and on trusty, so we will need to perform separate builds on Launchpad in the future rather than copying the binary from precise to trusty. The existing Debian metadata supports this with no changes, and I expect this to be fixed next time we build Launchpad packages."

Misc release tasks
- [ ] ~~Use semver.org numbering, starting with `2.1.0`, as per [request from homebrew]~~(https://github.com/Homebrew/homebrew/pull/33174/files#r18952984)
- [x] Fix UI breakage https://github.com/fontforge/fontforge/issues/1552 
- [x] Fix UI breakage https://github.com/fontforge/fontforge/issues/1622
- [ ] ~~`make install` to check if python `.so` already installed (as per https://github.com/fontforge/fontforge/issues/1496#issuecomment-49324552)~~

Crash reporting
- [x] https://github.com/fontforge/fontforge/issues/74 add breakpad (Discussed in https://github.com/fontforge/fontforge/issues/1212 and https://github.com/fontforge/fontforge/issues/1250 and https://github.com/fontforge/fontforge/issues/910 (win)) @monkeyiq is working on this

Do a release
- [x] Follow the documented process to make a release, adding anything that was missing
- [x] Tag a pre-release

**Comment by davelab6** [comment]
> Use semver.org numbering, starting with 2.1.0, as per request from homebrew

@frank-trampe says we can't do this because the 20140731 (eg) number is greater than two point something and that will break homebrew. so we're stuck with date versioning until homebrew gets 'epoch' version numbering as .deb and .rpm have to work around this.

**Comment by davelab6** [comment]
@adrientetar I moved your 3 issues to the feb release issue, #2083
