### ISSUE TITLE
Remove outlines and more padding on Tools Pallet 

### ISSUE THREAD

**Issue by pathumego** [fontforge/fontforge#1827]
Graphics
- [x] Create new icons
- [x] Paletteselectedbg.png
- [x] Mouse icon instead of Mse-stuff

Code
- [ ] Support for theme-adjustable palette margins + spacing
- [ ] Support for Paletteselectedbg.png (https://github.com/fontforge/fontforge/issues/1827#issuecomment-97260391)
- [ ] Support for the proposed restyling of Mse and make it "un-clickable"(https://github.com/fontforge/fontforge/issues/1827#issuecomment-98128014) + (https://github.com/fontforge/fontforge/issues/1456)
- [ ] Change the order of the palette icons a bit (https://github.com/fontforge/fontforge/issues/1827#issuecomment-98878311)
- [ ] Use visiblility_off/on.png as default instead of them ugly eyes.

Previously
- [x] <strike>Removing the outlines on the toolbar pallet button would make a pleasant difference. And add 2px padding would be needed.</strike> (see below)

- [x] ~~The eye icon is clipped on layers panel, maybe increase of the width would fix that.~~

**Comment by andreaslarsen** [comment]
What I think needs to be done is not use active icons but have a palleteselectedbg.png that gets put behind any icon when it's selected (also the spire toggle which currently has "up + down")

**Example**

paletteruler.png

![screen shot 2015-04-29 at 01 14 54](https://cloud.githubusercontent.com/assets/3859425/7382274/3a6cc584-ee0d-11e4-9976-01045af65521.png)

palleteselectedbg.png

![screen shot 2015-04-29 at 01 15 01](https://cloud.githubusercontent.com/assets/3859425/7382283/5618da8e-ee0d-11e4-8ee9-4cbcb95ad712.png)

selected and unselected state

![screen shot 2015-04-29 at 01 15 16](https://cloud.githubusercontent.com/assets/3859425/7382290/65497aea-ee0d-11e4-956d-85b788bc80df.png)

**Comment by andreaslarsen** [comment]
Shown together with a couple of more icons


![screen shot 2015-04-29 at 01 19 00](https://cloud.githubusercontent.com/assets/3859425/7382321/c3271c1c-ee0d-11e4-9348-1ae246b38d51.png)

**Comment by davelab6** [comment]
Agree

**Comment by andreaslarsen** [comment]
maybe keep up+down for the spiro toggle though since it's a bit different than the others though

**Comment by andreaslarsen** [comment]
The spiro toggle could also be placed on top like so:

![screen shot 2015-04-29 at 12 39 08](https://cloud.githubusercontent.com/assets/3859425/7389285/c68d2b08-ee6c-11e4-8688-1414a7492969.png)
![screen shot 2015-04-29 at 12 38 57](https://cloud.githubusercontent.com/assets/3859425/7389286/c6af670e-ee6c-11e4-87b1-8c9505e7d76e.png)

**Comment by pathumego** [comment]
@andreaslarsen  you mean on the very top of the toolbox?

**Comment by davelab6** [comment]
Yeah I like that

**Comment by andreaslarsen** [comment]
makes more sense to me too...only problem is the resulting uneven number of buttons :smile:

**Comment by davelab6** [comment]
"Make line"  could be a useful button

**Comment by andreaslarsen** [comment]
In the following buttons are all icons except the spiro icon which is a toggle

If we should prioritise it I'd say:

- [] Add support for palleteselectedbg.png on all buttons
- [] Move the toggle to the top (no palleteselectedbg.png - just updated up/down images)
- [] Maybe rearrange the icons a bit (e.g. zoom and hand which belong at the bottom in the hierarchy imo)
- [] Add "make line" and/or some other(s)

**Comment by andreaslarsen** [comment]
Just had to try how it looked in dark :wink: 

![1](https://cloud.githubusercontent.com/assets/3859425/7393521/9e19347e-ee8e-11e4-805d-7b51cfb2dcaa.png)  ![2](https://cloud.githubusercontent.com/assets/3859425/7393522/9e1a0bb0-ee8e-11e4-9c96-fb2ac862baf3.png)  ![3](https://cloud.githubusercontent.com/assets/3859425/7393520/9df836ca-ee8e-11e4-9d04-a7fcfa10b9bd.png)

**Comment by andreaslarsen** [comment]
Measurements (I haven't tested what they currently are)

![metrics](https://cloud.githubusercontent.com/assets/3859425/7393804/19282462-ee90-11e4-8419-ff52b0647292.png)

**Comment by andreaslarsen** [comment]
![screen shot 2015-04-29 at 20 10 38](https://cloud.githubusercontent.com/assets/3859425/7398476/90779966-eeaf-11e4-8a7a-4f8c4e34d6c9.png)  old vs new  ![yosemiforgepallette](https://cloud.githubusercontent.com/assets/3859425/7398951/aab279ce-eeb2-11e4-93b9-f024332b41fe.png)

I tried color coding the icons

yellow: transform
white: doesn't edit anything
red: add points

And a different layout in the bottom with icon instead of Mse1 abbreviations. Thoughts?

**Comment by davelab6** [comment]
BRILLIANT!! :)

**Comment by andreaslarsen** [comment]
colors more in sync
![yosemiforgepallette](https://cloud.githubusercontent.com/assets/3859425/7410744/148494ac-ef32-11e4-8922-4516e8f2c41f.png)

**Comment by andreaslarsen** [comment]
**Increasing padding:**

I had a quick look in [cvpalettes.c](https://github.com/fontforge/fontforge/blob/master/fontforgeexe/cvpalettes.c) I think these need to be change (@frank-trampe or some else knowledgeable please comment/look into this)

Icon size 25*25
Icon spacing left 3, between 4, right 3
Icon spacing above, between and below 4

#define CV_TOOLS_WIDTH		(3+25+4+25+3)
#define CV_TOOLS_HEIGHT	(4+10*(25+4)+2+4*12+2)
#define BV_TOOLS_WIDTH		same as cv?
#define BV_TOOLS_HEIGHT		?

icon placement
line 896
mouse clicks
line 1108?
bvtools icon placement
line 3940
BVToolsMouse
line 4024

**paletteselectedbg.png**
also 25*25
needs to be put behind a selected tool (and not spiroup/spirodown)

**Mse1 etc replacement**
palettemouse.png - 54 wide, 42 tall; spacing around 3
palettesmall*.png - 21x21; spacing left 3, between 12, right 3; spacing above 3, between 0, below 3

**Comment by andreaslarsen** [comment]
Full dark set:

![yosemiforgepallette](https://cloud.githubusercontent.com/assets/3859425/7432273/fac99ad0-f026-11e4-8576-bcf165992f39.png)

**Comment by adrientetar** [comment]
Nice work – I could need some artwork when my software is ready to use.

**Comment by andreaslarsen** [comment]
Cheers, just contact me when time comes

**Comment by adrientetar** [comment]
![gv](https://cloud.githubusercontent.com/assets/1250894/7444907/e9e2be48-f19a-11e4-9eb2-cf8154ad3cf2.PNG)

The colors could be better for sure though.

**Comment by davelab6** [comment]
Wow, looks great!! Is this python or c++? :)

**Comment by adrientetar** [comment]
It's Python with PyQt.

**Comment by davelab6** [comment]
I'm excited to see it launch :) Are you done with school for the summer? :)

**Comment by adrientetar** [comment]
Well I'm passing competitive exams right now and then we have followup courses at school.

**Comment by frank-trampe** [comment]
I don't think that we can change the defined toolbar dimensions without breaking other people's themes. Perhaps we need to let themes define those values?

**Comment by davelab6** [comment]
> without breaking other people's themes

I'm okay with that. Onwards!

**Comment by davelab6** [comment]
@frank-trampe and I discussed this briefly; Frank is concerned that people with their own (public/private) themes will have change aversion and be angry and upset if we push this change. I am concerned that if we don't ship this change soon then @andreaslarsen will lose interest in contributing, and his theme is **simply much better** so people who are maintaing themes will simply have to update them to the new layout - and this update is quite easy to do, since it just means adjusting the canvas size of their existing icons with additonal transparent pixels. 

However, @frank-trampe things that making it possible for theme files to define those values, so that no old themes break, will not be too much effort and he is volunteering to do it, so, we'll see what he can cook up shortly :)

**Comment by frank-trampe** [comment]
Actually, why do the new icons need to be a pixel wider in the first place? Was that intentional?

It's customary to have icon sizes as powers of two or small multiples of powers of two, and I'd like to maintain that standard if at all possible.

**Comment by davelab6** [comment]
> why do the new icons need to be a pixel wider in the first place? Was that intentional?

I believe it was. The reason they need to be a pixel wider can be seen in the comparison:

> ![screen shot 2015-04-29 at 20 10 38](https://cloud.githubusercontent.com/assets/3859425/7398476/90779966-eeaf-11e4-8a7a-4f8c4e34d6c9.png)  old vs new  ![yosemiforgepallette](https://cloud.githubusercontent.com/assets/3859425/7398951/aab279ce-eeb2-11e4-93b9-f024332b41fe.png)

**Comment by andreaslarsen** [comment]
the reason for them being uneven number is to have a centre line - they could be redrawn to fit 24px but will either loose some crispness/sharpness or may appear a bit off centre - if that makes sense?

**Comment by davelab6** [comment]
Centering them is another great reason!

**Comment by andreaslarsen** [comment]
but if everything will be adjustable in the theme file then icon size shouldn't matter anyway?

**Comment by frank-trampe** [comment]
Indeed, but I wanted to save the trouble if it wasn't necessary. I'd never seen odd-size icons before, so I had to ask.

Compared to the other required supporting changes, implementing adjustable icon size is a rather small task.

**Comment by andreaslarsen** [comment]
If made theme-able then the values needed for the top part of the palette would be:

* margin-top, bottom, left, right
* inter-icon-spacing horizontal and vertical

**Comment by andreaslarsen** [comment]
@frank-trampe - any thoughts on my proposal for the mouse icon instead of Mse1 names?

**Comment by andreaslarsen** [comment]
I don't know anything about how the UI in FontForge works/doesn't work - but do we need absolute values for palette width and height? 

Couldn't the values (margin + spacing) be defined in the c-file and then any icon size could be used? 

So that palette width and height (and clickable areas) is automatically calculated?

**Comment by frank-trampe** [comment]
@andreaslarsen, I don't entirely understand the Mse replacement. Is the top set of actions for unshifted click (left and right), with the bottom for shifted click (left and right)? If a modifier such as shift or control is pressed, does this change?

**Comment by frank-trampe** [comment]
Spacing would cease to be universal with the adoption of this theme, so we would need a definable value for spacing. And once one of the values goes into the configuration file, I think that it is less confusing for the theme designer if all values do so.

**Comment by andreaslarsen** [comment]
I'm not sure I understand your question about Mse1 - the icons should work just as they do now?

I thought ^ = ctrl and not shift or some other modifier?

**Comment by frank-trampe** [comment]
The current version of FontForge does not have that mouse thing in the toolbar, and I assume that the mouse-looking thing in your new rendering somehow relates to the Mse functionality.

And, yes, you're right about ^. Sorry for the confusion.

**Comment by andreaslarsen** [comment]
ok
upper icons = unmodified click
bottom icons = click with ctrl pressed down

**Comment by andreaslarsen** [comment]
so the icons are the same as
mse1    mse2
mse1^  mse2^

**Comment by frank-trampe** [comment]
And the Ctrl caption is static, then, rather than reflective of currently pressed modifiers?

**Comment by andreaslarsen** [comment]
isn't it currently static?

**Comment by andreaslarsen** [comment]
the cursor changes when I press ctrl but the mse icons doesn't change

**Comment by frank-trampe** [comment]
It doesn't exist in current FontForge.

It isn't immediately clear (at least to me) what the new diagram means (not that the current indicators are more obvious). Perhaps something like this would be clearer.

```
    ___
   / | \
  |     |
   \___/
     +
<- ctrl ->
```

Or maybe I'm just not very intuitive. Other perspectives on this?

**Comment by andreaslarsen** [comment]
but isn't mse2 the third button and not right click? 
I could add the plus between the mouse and ctrl but I omitted it initially since it still needs some explaining anyway so I figured I'd make it as minimal as possible

**Comment by frank-trampe** [comment]
You're right about that too. I've never understood the Mse portion of the toolbar. But then the mouse icon as you've placed it makes me think that Mse2 is the right mouse button.

**Comment by andreaslarsen** [comment]
ok, that's why I've tried to highlight the left click and middle click of the mouse - but I could make those more highlighted so this is clearer

**Comment by frank-trampe** [comment]
I couldn't tell that the middle button was highlighted.

**Comment by andreaslarsen** [comment]
![screen shot 2015-05-04 at 23 51 25](https://cloud.githubusercontent.com/assets/3859425/7463284/84edb1f4-f2b8-11e4-8a31-7d67d49c6888.png)
 now?

**Comment by frank-trampe** [comment]
That's clear.

**Comment by andreaslarsen** [comment]
:+1: I'll update or make a new pr soon. 

@frank-trampe when you're already looking at the cvpalettes.c file: what do you think about rearranging the icons a bit?
I've tried to color theme the icons based on their function. To me, this order makes most sense a follow the conventions used by most other graphic editors:

![screen shot 2015-05-05 at 00 14 38](https://cloud.githubusercontent.com/assets/3859425/7463693/d8d596da-f2bb-11e4-81dc-393f7f57ffde.png)

**Comment by andreaslarsen** [comment]
I've updated #2245 with the a new mouse icon and I'll take the liberty of editing the to do list in @pathumego initial post so we better can see what's done and what needs to be done.

**Comment by andreaslarsen** [comment]
details about the order:

* white ones: The order between the 4 of them is unimportant so if any of you think we should swap e.g. hand and zoom - ok by me.
* red ones: I've tried doing a couple of things
  * The three icons that (almost) doesn't change between spiro+bezier stay in the same place. 
  * I've deliberately made it so that the diamond shaped ones aren't in the same spot, since they are two very different point types. 
  * I've put the two tangent icons in spiro mode next to each other
  * Freehand + knife doesn't change at all so they are together. I've put them after the other six red ones but they could also be placed above those.
*  transform + add shape icons - I'm actually inclined to think the blue ones should come before the yellow+green ones but that's not so important.

The six red ones i bezier mode:
![screen shot 2015-05-05 at 00 47 18](https://cloud.githubusercontent.com/assets/3859425/7464120/56981878-f2c0-11e4-9e3b-7e79b4b1bde4.png)

The six red ones i spiro mode:
![screen shot 2015-05-05 at 00 47 21](https://cloud.githubusercontent.com/assets/3859425/7464127/6aa15e6a-f2c0-11e4-90e2-9afd42bd43f3.png)

**Comment by frank-trampe** [comment]
I think that we can change the icon arrangement without breaking anything since the current theme format makes no guarantees about icon placement. As to whether it's user-friendly, I would need to defer to people who use FontForge more seriously than I do. @davelab6, @pathumego?

The outlines on the icons are showing up as not black to me. I thought that it was my monitor, but I just opened one of the files in the GIMP, and they are indeed not black. Was that intentional?

**Comment by andreaslarsen** [comment]
About arrangement: I skimmed through the cvpalettes.c file and think I saw I comment about "if you change the order then remember to also change it ... something, something I couldn't understand". 

The outlines for the light version aren't black. Looks too harsh on a bright background :)

**Comment by andreaslarsen** [comment]
This was the "something, something thing..." https://github.com/fontforge/fontforge/blob/master/fontforgeexe/cvpalettes.c#L293

**Comment by pathumego** [comment]
@frank-trampe I think new structure is much better. it is logical and also should be easier. I just showed it to a another friend who works with me. They think the same :)

**Comment by pathumego** [comment]
@davelab6 I agree that shipping these changes is a must :) And can this be the default theme?

**Comment by frank-trampe** [comment]
@pathumego, the pull request is implemented as a change to tango, which I believe is the default theme.

**Comment by davelab6** [comment]
> tango, which I believe is the default theme

Yes

**Comment by pathumego** [comment]
@adrientetar im just curious.. so your programme posted here would support Robofont extensions? ;)

**Comment by davelab6** [comment]
@pathumego depends on the extension; RoboFont has the `mojo` library and the `vanilla` ui library, which some RoboFont extensions require. Its possible for Adrien to provide replacements for these, of course. But other scripts that are pure robofab/defcon will work.

**Comment by adrientetar** [comment]
What Dave said. Note that I do not intend to provide replacements to these libraries for now and my defconQt makes no compatibility guarantees with defconAppkit.

**Comment by pathumego** [comment]
@larsenwork whats the status of this now? :)

**Comment by larsenwork** [comment]
https://github.com/fontforge/fontforge/pull/2245

**Comment by pathumego** [comment]
Closing, See #2396

**Comment by adrientetar** [comment]
@larsenwork Do you wish to create icons for the project? If so tell me and I'll send you the details.

**Comment by frank-trampe** [comment]
@adrientetar, @andreaslarsen has already made the icons. They are awaiting some long-overdue support code from me right now.

**Comment by adrientetar** [comment]
Oh I was speaking of the new software I am working on, soz.
