### ISSUE TITLE
2015-01 Release

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#1985]
(Moving some things from https://github.com/fontforge/fontforge/issues/1805 that won't make december to here)

Cleanup Issues
- [ ] https://github.com/fontforge/fontforge/labels/I-cleanup
- [ ] Find all build errors reported in this issue tracker so far and list them here

Completion Issues
- [ ] https://github.com/fontforge/fontforge/labels/I-completion

Mac
- [ ] The FontForge shell script should check the X11 key preference, and if it isn't set right, ask to change it, and then change it, before starting FF [#1764](https://github.com/fontforge/fontforge/issues/1764)

Windows
- [ ] configure to be updated so collab works on win, https://github.com/fontforge/fontforge/issues/1804

Misc
- [ ] source package builder shell script added to repo (for automaking making builds for all platforms.) 
- [ ] bring in `libspiro` as a git submodule?

Crash Reporter
- [ ] https://github.com/fontforge/fontforge/issues/74 add better breakpad reports (Discussed in https://github.com/fontforge/fontforge/issues/1212 and https://github.com/fontforge/fontforge/issues/1250 and https://github.com/fontforge/fontforge/issues/910 (win)) @monkeyiq is working on this

Auto Updater
- [ ] Provide an AppCast RSS URL on <FontForge.github.io> and
- [ ] use sparkle in the mac bundle and 
- [ ] use winsparkle in the windows build

Spiro
- [ ] make a new release of libSpiro
- [ ] update libSpiro for mac builds
- [ ] update libSpiro for win builds

Ideas
- Set up the FontForge git repo like http://nvie.com/posts/a-successful-git-branching-model/ for nicely made releases?
- [ ]  Breakpad working on Windows
- [ ]  iPython working on Windows
- [ ]  https://github.com/fontforge/fontforge/issues/911 win collab working (est: 1 hour)
- [ ]  PyQT working on Windows
- [ ] New PyQT Point Info working on Windows

Do a release
- [ ] Set up Travis to automatically post DEB and RPM binaries to the PPA and FedoraPeople repos using http://docs.travis-ci.com/user/deployment/custom/ 
- [ ] Set up Travis to build windows setups for the [FF community server](`fontforge.default.fontforge.uk0.bigv.io`) ?

**Comment by skef** [comment]
Barn door.
