### ISSUE TITLE
2015-02 Release

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2083]
https://github.com/fontforge/fontforge/wiki/Making-a-release describes the process for making a release, so lets follow that after closing the following:

Misc release tasks
- [ ] ~~Merge all pull requests - https://github.com/fontforge/fontforge/pulls~~ punted to next release
- [x] Build `make install` to check if python `.so` already installed (as per https://github.com/fontforge/fontforge/issues/1496#issuecomment-49324552)
- [ ] ~~UFO fix export https://github.com/fontforge/fontforge/issues/2073~~ punted to next release
- [x] ~~UFO prevent overlap removal #1008~~ (removed as not related to UFO)
- [ ] ~~Python add script to fix path direction on UFO export for FDK #1995~~ punted to next release or later
- [x] Metrics window bugs #1622
- [x] Update PPA to work well #2005 @frank-trampe 
- [x] ~~Update homebrew 10.10 crash #2023~~ punted to next release or later as homebrew builds ok for @davelab6
- [x] ~~Fix python #2085~~ @davelab6 couldn't reproduce so punted

Anything else urgent? :)

**Comment by adrientetar** [comment]
lgtm

**Comment by davelab6** [comment]
@dom4t In https://github.com/Homebrew/homebrew/commit/c41b11e255201fff22282d05f7266b35f3b9be8c#diff-4cce296cd74ea8d358eb7f3480aedaecL7 you removed the HEAD url, so we can't build FontForge's HEAD with homebrew.... confused about why, and hoping its a good idea to add it back :)

**Comment by davelab6** [comment]
I just tried to install via homebrew on a brand new OS X 10.9.5 installation:

```
$ brew install fontforge
==> Installing dependencies for fontforge: readline, sqlite, gdbm, openssl, python, libtool, gettext, libffi, glib, libpng, freetype, fontconfig, pixman
==> Installing fontforge dependency: readline
==> Downloading https://homebrew.bintray.com/bottles/readline-6.3.8.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring readline-6.3.8.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X provides similar software, and installing this software in
parallel can cause all kinds of trouble.

OS X provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
🍺  /usr/local/Cellar/readline/6.3.8: 40 files, 2.1M
==> Installing fontforge dependency: sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.8.8.3.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring sqlite-3.8.8.3.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

OS X provides an older sqlite3.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/sqlite/lib
    CPPFLAGS: -I/usr/local/opt/sqlite/include

==> Summary
🍺  /usr/local/Cellar/sqlite/3.8.8.3: 9 files, 2.1M
==> Installing fontforge dependency: gdbm
==> Downloading https://homebrew.bintray.com/bottles/gdbm-1.11.mavericks.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring gdbm-1.11.mavericks.bottle.2.tar.gz
🍺  /usr/local/Cellar/gdbm/1.11: 17 files, 532K
==> Installing fontforge dependency: openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssl-1.0.2.mavericks.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2: 459 files, 18M
==> Installing fontforge dependency: python
==> Downloading https://homebrew.bintray.com/bottles/python-2.7.9.mavericks.bottle.10.tar.gz
######################################################################## 100.0%
==> Pouring python-2.7.9.mavericks.bottle.10.tar.gz
==> Caveats
Setuptools and pip have been installed. To update them
  pip install --upgrade setuptools
  pip install --upgrade pip

You can install Python packages with
  pip install <package>

They will install into the site-package directory
  /usr/local/lib/python2.7/site-packages

See: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md

.app bundles were installed.
Run `brew linkapps python` to symlink these to /Applications.
==> /usr/local/Cellar/python/2.7.9/bin/python -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python/2.7.9/bin --instal
==> /usr/local/Cellar/python/2.7.9/bin/python -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python/2.7.9/bin --instal
==> Summary
🍺  /usr/local/Cellar/python/2.7.9: 4810 files, 78M
==> Installing fontforge dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libtool-2.4.6.mavericks.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6: 69 files, 3.8M
==> Installing fontforge dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.4.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring gettext-0.19.4.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X provides similar software, and installing this software in
parallel can cause all kinds of trouble.

OS X provides the BSD gettext library and some software gets confused if both are in the library path.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/gettext/lib
    CPPFLAGS: -I/usr/local/opt/gettext/include

==> Summary
🍺  /usr/local/Cellar/gettext/0.19.4: 1920 files, 21M
==> Installing fontforge dependency: libffi
==> Downloading https://homebrew.bintray.com/bottles/libffi-3.0.13.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libffi-3.0.13.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Some formulae require a newer version of libffi.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/libffi/lib

==> Summary
🍺  /usr/local/Cellar/libffi/3.0.13: 13 files, 388K
==> Installing fontforge dependency: glib
==> Downloading https://homebrew.bintray.com/bottles/glib-2.42.1.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring glib-2.42.1.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/glib/2.42.1: 410 files, 17M
==> Installing fontforge dependency: libpng
==> Downloading https://homebrew.bintray.com/bottles/libpng-1.6.16.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libpng-1.6.16.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libpng/1.6.16: 17 files, 1.3M
==> Installing fontforge dependency: freetype
==> Downloading https://homebrew.bintray.com/bottles/freetype-2.5.5.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring freetype-2.5.5.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/freetype/2.5.5: 60 files, 2.6M
==> Installing fontforge dependency: fontconfig
==> Downloading https://homebrew.bintray.com/bottles/fontconfig-2.11.1.mavericks.bottle.3.tar.gz
######################################################################## 100.0%
==> Pouring fontconfig-2.11.1.mavericks.bottle.3.tar.gz
==> /usr/local/Cellar/fontconfig/2.11.1/bin/fc-cache -frv
🍺  /usr/local/Cellar/fontconfig/2.11.1: 448 files, 3.6M
==> Installing fontforge dependency: pixman
==> Downloading https://homebrew.bintray.com/bottles/pixman-0.32.6.mavericks.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring pixman-0.32.6.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/pixman/0.32.6: 11 files, 1.4M
==> Installing fontforge dependency: cairo
==> Downloading https://homebrew.bintray.com/bottles/cairo-1.14.0.mavericks.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring cairo-1.14.0.mavericks.bottle.2.tar.gz
🍺  /usr/local/Cellar/cairo/1.14.0: 113 files, 6.6M
==> Installing fontforge dependency: icu4c
==> Downloading https://homebrew.bintray.com/bottles/icu4c-54.1.mavericks.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring icu4c-54.1.mavericks.bottle.1.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

OS X provides libicucore.dylib (but nothing else).

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include

==> Summary
🍺  /usr/local/Cellar/icu4c/54.1: 242 files, 65M
==> Installing fontforge dependency: harfbuzz
==> Downloading https://homebrew.bintray.com/bottles/harfbuzz-0.9.38.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring harfbuzz-0.9.38.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/harfbuzz/0.9.38: 72 files, 3.0M
==> Installing fontforge dependency: gobject-introspection
==> Downloading https://homebrew.bintray.com/bottles/gobject-introspection-1.42.0.mavericks.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring gobject-introspection-1.42.0.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/gobject-introspection/1.42.0: 196 files, 10M
==> Installing fontforge dependency: pango
==> Downloading https://homebrew.bintray.com/bottles/pango-1.36.8.mavericks.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring pango-1.36.8.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/pango/1.36.8: 132 files, 4.8M
==> Installing fontforge dependency: zeromq
==> Downloading https://homebrew.bintray.com/bottles/zeromq-4.0.5_2.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring zeromq-4.0.5_2.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/zeromq/4.0.5_2: 64 files, 2.8M
==> Installing fontforge dependency: czmq
==> Downloading https://homebrew.bintray.com/bottles/czmq-2.2.0_1.mavericks.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring czmq-2.2.0_1.mavericks.bottle.1.tar.gz
🍺  /usr/local/Cellar/czmq/2.2.0_1: 69 files, 1020K
==> Installing fontforge dependency: jpeg
==> Downloading https://homebrew.bintray.com/bottles/jpeg-8d.mavericks.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring jpeg-8d.mavericks.bottle.2.tar.gz
🍺  /usr/local/Cellar/jpeg/8d: 18 files, 780K
==> Installing fontforge dependency: libtiff
==> Downloading https://homebrew.bintray.com/bottles/libtiff-4.0.3.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring libtiff-4.0.3.mavericks.bottle.tar.gz
🍺  /usr/local/Cellar/libtiff/4.0.3: 254 files, 3.8M
==> Installing fontforge
==> Downloading https://homebrew.bintray.com/bottles/fontforge-20141230.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring fontforge-20141230.mavericks.bottle.tar.gz
Warning: fontforge dependency gettext was built with a different C++ standard
library (libc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/fontforge/20141230: 1291 files, 34M
$
```

**Comment by davelab6** [comment]
@twardoch and when I run it, I get just the python, no GUI. 
```
$ fontforge 
Copyright (c) 2000-2014 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 20:30 GMT 31-Dec-2014-D.
 Based on source from git with hash: 
>>> 
```

**Comment by DomT4** [comment]
@davelab6 Ugh, I'm an idiot. Sorry. Removing the head was accidental, I presume I meant to move it to the bottom of the first ` url/sha1 ` block, but evidently when I chopped the version out I also chopped the HEAD and forgot to put it back :crying_cat_face:. Apologies. Fix in https://github.com/Homebrew/homebrew/pull/37227.

**Comment by DomT4** [comment]
> I just tried to install via homebrew on a brand new OS X 10.9.5 installation:

You need to add ` --with-x11 ` to ` brew install fontforge `.

**Comment by davelab6** [comment]
@DomT4 with https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fontforge.rb#L17-L19 actually the Github tag's tarball will be ok for Homebrew - the super large tarball is for other build systems which disallow build processes to fetch things from the internet.

**Comment by DomT4** [comment]
Any thoughts on #2022 by the way?

**Comment by DomT4** [comment]
> actually the Github tag's tarball will be ok for Homebrew - the super large tarball is for other build systems which disallow build processes to fetch things from the internet.

The PR referenced a few comments up softens the wording around that.

**Comment by davelab6** [comment]
@DomT4 I guess adding the `install_name_tool` workaround will help for the moment?

**Comment by davelab6** [comment]
> The PR referenced a few comments up softens the wording around that.

Looks good!

**Comment by davelab6** [comment]
So to get a fully featured fontforge, one must `brew install jpeg libtiff giflib libspiro; brew install fontforge --with-x11;`

**Comment by DomT4** [comment]
>  I guess adding the install_name_tool workaround will help for the moment?

Yeah, It works. I just wanted to poke the issue and see if there's anything upstream here can do over a longer-term. We should be good to carry the workaround for a while longer if necessary.

> So to get a fully featured fontforge, one must

You can skip the first bit. Just ` brew install fontforge --with-x11 --with-giflib --with-libspiro `. Homebrew will pull in the deps automatically prior to installing Fontforge.

**Comment by davelab6** [comment]
> I just wanted to poke the issue and see if there's anything upstream here can do over a longer-term. 

Yep, I've got some @craftingtype workshops scheduled to raise funds to drive development forwards, and I want to focus on making the Breakpad integration solid so that we can hammer on crash fixes. 

> You can skip the first bit

Sweet!

**Comment by davelab6** [comment]
> ```Warning: fontforge dependency gettext was built with a different C++ standard
> library (libc++ from clang). This may cause problems at runtime.```

Is this a problem?

Additionally, the Homebrew version (top) looks different to the mac bundle version (bottom):

![screen shot 2015-02-26 at 2 14 38 pm](https://cloud.githubusercontent.com/assets/261579/6403108/e48d5348-bdc1-11e4-82df-81adfd34e82f.png)

**Comment by DomT4** [comment]
> Is this a problem?

Doesn't seem to be. The warning is there to flag up that it might be, but we haven't had any gettext related failures to date. It's originates from Fontforge's issues compiling with Apple's ` llvm ` compiler in the past.

> Additionally, the Homebrew version (top) looks different to the mac bundle version (bottom):

That's odd. Mine looks like this:

![screen shot 2015-02-26 at 22 17 37](https://cloud.githubusercontent.com/assets/6998367/6403241/d5ff1d4a-be05-11e4-9539-9507fdd7e5a1.png)

Looks like different fonts are being used perhaps, but I'm not sure where that would originate. It'll be an X11 quirk, I suspect... X11 has many quirks :smile_cat:.

**Comment by DomT4** [comment]
Going to take another look at the llvm situation. Maybe the newer Fontforges don't have the llvm problems the 2011 series did.

**Comment by DomT4** [comment]
Doesn't seem to look/act any different compiling Fontforge with an internal, compiler-harmonised version of ` gettext `, so presuming that's not the cause:

![screen shot 2015-02-27 at 00 33 56](https://cloud.githubusercontent.com/assets/6998367/6405194/6e9a6caa-be18-11e4-9f9a-6402671f7f99.png)

**Comment by davelab6** [comment]
> Mine looks like this:

Yours and mine look the same. The default theme sources are there, but it look like the homebrew version isn't using them. 

```
$ ls -1 /usr/local/share/fontforge/pixmaps/*ttf
/usr/local/share/fontforge/pixmaps/Cantarell-Bold.ttf
/usr/local/share/fontforge/pixmaps/Cantarell-BoldOblique.ttf
/usr/local/share/fontforge/pixmaps/Cantarell-Oblique.ttf
/usr/local/share/fontforge/pixmaps/Cantarell-Regular.ttf
/usr/local/share/fontforge/pixmaps/Inconsolata-Bold.ttf
/usr/local/share/fontforge/pixmaps/Inconsolata-Regular.ttf
$ ls -1 /Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/*ttf
/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/Cantarell-Bold.ttf
/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/Cantarell-BoldOblique.ttf
/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/Cantarell-Oblique.ttf
/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/Cantarell-Regular.ttf
/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/Inconsolata-Bold.ttf
/Applications/FontForge.app/Contents/Resources/opt/local/share/fontforge/pixmaps/Inconsolata-Regular.ttf
$
```

**Comment by DomT4** [comment]
The settings seems to be pointing at the right folder:

![screen shot 2015-02-27 at 01 26 10](https://cloud.githubusercontent.com/assets/6998367/6405778/b54bddc6-be1f-11e4-8159-a1fb2adfee1b.png)

Something funky happens though if you actually select the resources file rather than just the folder, and then exit out of Fontforge and reload it...

![screen shot 2015-02-27 at 01 26 25](https://cloud.githubusercontent.com/assets/6998367/6405783/c1f95bb6-be1f-11e4-8379-a6ab94695a5b.png)

The whole thing turns a shade of blue, and it doesn't go away. :confounded:

**Comment by davelab6** [comment]
that's the default theme hehe

**Comment by DomT4** [comment]
Of X11 or Fontforge?

**Comment by davelab6** [comment]
The default theme of Fontforge; the founder has unusual color vision.

**Comment by DomT4** [comment]
Oh, so is the behaviour in this case correct? In terms of finding and using the correct resources? It isn't broken?

**Comment by adrientetar** [comment]
Is this the same issue as we had with Debian/Ubuntu ppas, that the theme files are not copied properly by the installer? In the case of debian, it was fixed by n7s.

**Comment by davelab6** [comment]
Sorry, I see the way I expressed this is confusing... 

By the 'default theme' I meant the way widgets look by default in the underlying X Window Toolkit, that was written George Williams, the founder of FontForge. GWW wrote that toolkit from scratch for FontForge, and no other programs use it. This default is slightly blue with bright yellow highlights, and was what GWW wanted because his color vision is unusual. 

FontForge now bundles a theme file - https://github.com/fontforge/fontforge/blob/master/fontforgeexe/pixmaps/tango/resources - which uses the theming features of the toolkit to override that 'default theme' to look slightly more familiar to GNOME and Mac users.

**Comment by adrientetar** [comment]
> and the PPA currently does not, but I expect @frank-trampe to cut a release in the next day or two and thus fix the PPA

Really? I thought this was fixed by the PRs of n7s.

**Comment by davelab6** [comment]
Until Frank makes a release the PPA isn't updated

**Comment by adrientetar** [comment]
Right, I misunderstood.

**Comment by davelab6** [comment]
@frank-trampe 3 issues with your name on them at the top now :)

**Comment by davelab6** [comment]
@frank-trampe what's the status of the tasks at the top?

**Comment by davelab6** [comment]
@jtanx @monkeyiq https://github.com/fontforge/fontforge/releases/tag/20150228 is ready for you to build win and mac packages for :)

**Comment by DomT4** [comment]
> This default is slightly blue with bright yellow highlights, and was what GWW wanted because his color vision is unusual.

Thanks for the explanation, I had no idea! I've never come across the default Fontforge theme before now, so it's possible the resource wasn't applying completely cleanly until I actually went and selected the resource file, perhaps. Agreed the font still looks off, but I haven't yet found the root cause of that frustratingly. I guess at least it's not a critical error, even if it is kinda frustrating.

I'll push the new tag into Homebrew tonight.

**Comment by DomT4** [comment]
Oh, It's been tagged pre-release. Is it stable or should I wait till it's officially a "release"?

**Comment by frank-trampe** [comment]
I didn't tag it as a pre-release. Dave may have done that until we have binaries posted. Go ahead and push it.

**Comment by davelab6** [comment]
Yes, that's why I set it to pre-release

**Comment by DomT4** [comment]
Cool. There's a PR open at Homebrew for it now, the same PR I opened for the HEAD issue the other day that got stuck behind some automated machine testing issues, so I just repurposed the PR. (Still contains the HEAD fix).

**Comment by jtanx** [comment]
@davelab6 sorry for the delay, I didn't realise there was a release. It should be updated now :)

**Comment by davelab6** [comment]
Thanks @jtanx !!!

**Comment by DomT4** [comment]
Homebrew is updated :+1:

**Comment by davelab6** [comment]
@monkeyiq made a fuuko package, it installs, so I marked the release as done

**Comment by DomT4** [comment]
Re fontconfig discussion. We perhaps have found a reproducible test case outside of Fontforge as well - https://github.com/Homebrew/homebrew/issues/37803. So you may well be right about Brewed Fontconfig being... different, for some reason.

**Comment by davelab6** [comment]
Wow! @drizt thank you so much for digging into this!!! :) Had to be one of those cray-zee emacs guys to figure it out!! :dart:

**Comment by frank-trampe** [comment]
@DomT4, is there any chance that you could try this linked each way and see whether one performs or behaves differently from the other?

**Comment by DomT4** [comment]
I spent an hour hunting through X11 source code yesterday trying to find some explanation of how they build Fontconfig so I can see any differences. Sadly, X11's source code is a deep, dark, twisty, frustrating maze :smile_cat:. I'm hoping to find the configure options, and compare them. If that doesn't gain anything, I'll try different compilers. It has to be something in the build process.

I'll try building FontForge against X11's Fontconfig later tonight and see whether the lettering problem is fixed.

**Comment by DomT4** [comment]
This is proving somewhat fun. Homebrew's build system specifically priorities everything above ` x11 `, and undoing vast chunks of that for this test breaks FontForge's compile entirely. I'll probably have to take it outside of the ` brew ` sandbox and compile it manually, using individual CFLAGS and such to ensure various libraries are chosen over others.
