### ISSUE TITLE
Ensure FontForge passes Spot's Project Checklist

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2138]
http://fossil-scm.org/index.html/doc/trunk/www/foss-cklist.wiki offers a checklist for free software projects:

- [ ] The source code size is less than 100 MB, uncompressed.

- [ ] The project uses a Version Control System (VCS).
    - [ ] The VCS has a working web interface.
    - [ ] There is documentation on how to use the VCS.
    - [ ] The VCS is general-purpose, not something hacked together for this one project. 

- [ ] The project comes with documentation on how to build from source and that documentation is lucid, correct, and up-to-date.

- [ ] The project is configurable using an autoconf-generated configure script, or the equivalent, and does not require:
    - [ ] Manually editing flat files
    - [ ] Editing code header files 

- [ ] The project should be buildable using commonly available and standard tools like "make".

- [ ] The project does not depend on 3rd-party proprietary build tools.

- [ ] The project is able to dynamically link against standard libraries such as zlib and libjpeg.
    - [ ] The project does not ship with the sources to standard libraries. (On the Fossil project, we will allow the SQLite library sources to be included in the source tree as long as a system-installed SQLite library can be used in its stead.)
    - [ ] The project does not use slightly modified versions of standard libraries. Any required bug fixes in standard libraries are pushed back upstream. 

- [ ] "make install" works and can be configured to target any directory of the installer's choosing.
    - [ ] The project contains no unconfigurable hard-coded pathnames like "/opt" or "/usr/local".
    - [ ] After installation, the source tree can be moved or deleted and the application will continue working. 

- [ ] The source code uses only \n for line endings, not \r\n.

- [ ] The code does not depend on any special compiler features or bugs.

- [ ] The project has a mailing list and announces releases on the mailing list.

- [ ] The project has a bug tracker.

- [ ] The project has a website.

- [ ] Release version numbers are in the traditional X.Y or X.Y.Z format.

- [ ] Releases can be downloaded as tarball using gzip or bzip2 compression.

- [ ] Releases unpack into a versioned top-level directory. (ex: "projectname-1.2.3/").

- [ ] A statement of license appears at the top of every source code file and the complete text of the license is included in the source code tarball.

- [ ] There are no incompatible licenses in the code.

- [ ] The project has not been blithely proclaimed "public domain" without having gone through the tedious and exacting legal steps to actually put it in the public domain.

- [ ] There is an accurate change log in the code and on the website.

- [ ] There is documentation in the code and on the website.

**Comment by mskala** [comment]
On Wed, 11 Mar 2015, Dave Crossland wrote:
>     The project has not been blithely proclaimed "public domain" without
>     having gone through the tedious and exacting legal steps to actually put
>     it in the public domain.

This isn't applicable to FontForge anyway, but it's wrong, and casts doubt
on anything else the "Spot Project" says.

-- 
Matthew Skala
mskala@ansuz.sooke.bc.ca                 People before principles.
http://ansuz.sooke.bc.ca/

**Comment by davelab6** [comment]
Tom 'spot' Callaway was the fedora engineering manager for a few years and he seemed to know about such things...
