### ISSUE TITLE
Redesign the menu structures of the 3 main windows

### ISSUE THREAD

**Issue by davelab6** [fontforge/fontforge#2257]
EDIT: @pathumego, @davelab6 and @andreaslarsen are currently trying to figure things out in [this](https://docs.google.com/document/d/18UVeLOq-s_qJ_5IFbR8qHjHVufwk72KaLuI05WJNAWA/edit?usp=sharing) google doc. Feel free to comment and make suggestions there.

What we're trying to do (WIP)
-----
- [ ] Making the 3 menus identical (except for what's grey'd out) 
- [ ] Rearranging items so things are easier to find
- [ ] Renaming items to more understandable names
- [ ] No level below top-level -> submenu -> item
- [ ] Updating tooltip text #2259
- [ ] Re-arrange/name right click menus incl. #2261

**Removing some items**
- [ ] Browse web (broken)
- [ ] X-resource editor (https://github.com/fontforge/fontforge/issues/2260)

What we later need a software developer for
-----
- [ ] Implement the changes (or tell us how)

**Comment by andreaslarsen** [comment]
@pathumego and discussed this in his google doc - I will post the gist of it here :smile:

**Comment by andreaslarsen** [comment]
So top level could be something like this:

| Fontview |      |         |         |          |        |        |      |
|----------|------|---------|---------|----------|--------|--------|------|
| File     | Edit | Element | Tool    | Encoding | View   | Window | Help |

| Charview |      |         |         |          |        |        |
|----------|------|---------|---------|----------|--------|--------|
| File     | Edit | Element | Point   | View     | Window | Help   |      

| Metrics  |      |         |         |          |        |        | 
|----------|------|---------|---------|----------|--------|--------|
| File     | Edit | Element | Metrics | View     | Window | Help   |

**Comment by andreaslarsen** [comment]
Hmm...GitHub tables are a mess so I created a new doc only about the menu rearranging

https://docs.google.com/document/d/18UVeLOq-s_qJ_5IFbR8qHjHVufwk72KaLuI05WJNAWA/edit?usp=sharing

**Comment by davelab6** [comment]
I propose there should be a single menu structure for all windows.

That way users don't need to remember which window to find the item in

**Comment by andreaslarsen** [comment]
Yes, I thought about that too...I missed tool in the last two above. And I think, as written i the doc, that metrics shouldn't be a top level item. 

Then only encoding and point (which are highly view specific) differs

**Comment by davelab6** [comment]
I suggest to have the point menu in all windows, but have them disabled
where it can't be used

Encoding can be used from any window though

**Comment by pathumego** [comment]
@davelab6 Agree I was first confused when the menues were different on each window.

**Comment by pathumego** [comment]
@andreaslarsen  I added right click context Menues into doc.

**Comment by pathumego** [comment]
cc @kosalaya

**Comment by pathumego** [comment]
This is being developed and discussed further here:

https://docs.google.com/document/d/18UVeLOq-s_qJ_5IFbR8qHjHVufwk72KaLuI05WJNAWA/edit

**Comment by andreaslarsen** [comment]
This doesn't relate that much to the menu redesign but maybe we should stop calling it FontView, GlyphView/CharView, Metrics View (also in documentation such as designwithFF) and instead call them

Font Window
Glyph Window
Metrics Window

They are windows after all and you click the menu item window to open them (and only there...) - not views. 
@davelab6 ?

**Comment by davelab6** [comment]
View is from the source code, like in MVC. I'm happy to use window only for
all ui and docs

**Comment by andreaslarsen** [comment]
Great, then we can also remove "Metrics" -> "New Metrics Window" right ? ;)

**Comment by andreaslarsen** [comment]
:+1:

**Comment by davelab6** [comment]
I think it's a good idea but if you don't believe me let's pull it out and do some user tests

**Comment by pathumego** [comment]
We will have to think about a rollout plan down the line. Documentation and interface docs along with DWFF will have to be updated.

**Comment by andreaslarsen** [comment]
Yep, I took the liberty of updating the first post and try to write to-do of what we are trying to accomplish. 

I think it's fastest if we you try and get the menu just like we want it (in google doc) and then at the end write down details about what needs to be changed in the code to reflect those changes.

**Comment by pathumego** [comment]
@andreaslarsen ok so I thinkits getting into shape. So major changes to finalise.

-  [ ]  'Add Encoding Slots' into Add Glyphs (and related items)
-  [ ]  FontForge menu

**Comment by andreaslarsen** [comment]
@pathumego I think we shall keep details like "rename this to that" in the doc for now - it will be a long list in the end ;) 
I added the FontForge menu to the todo list though since I'm still unsure about it.

**Comment by pathumego** [comment]
Agreed :)

**Comment by andreaslarsen** [comment]
@davelab6 After a nights sleep I'm very unsure about adding that "FontForge" before "File"

It is a standard on mac but only for menu bars - this isn't really a menu bar - that's the X11 bar.

And since I don't think any other X11 apps use it I think the benefit on mac is limited and it would just confuse win users

**Comment by davelab6** [comment]
Okay cool - was just a proposal. Please remove :)

**Comment by andreaslarsen** [comment]
I just did (kept as proposal down on page 3 :)

**Comment by andreaslarsen** [comment]
As a general thing what do you guys think about e.g.

```
Export
    Fonts
    Mac Family
    TTC’
    UFO
```
instead of
```
Export
    Export Fonts
    Export Mac Family
    Export TTC’
    Export UFO
```

(same concept for clear, copy, select, revert etc.)

**Comment by davelab6** [comment]
I think it would be better to have simply,
```
Export
Export Formats >
    TTC
    Mac Family
```

**Comment by andreaslarsen** [comment]
So `Export` = `Export Font` ? 

But ttf, otf, etc. are also formats

**Comment by ultrasquid** [comment]
Call me a stick in the mud, but I'd prefer something more old-fashioned,
with a bit of refinement:

Save As…
     sfd
     sfdir
     ufo
     other font editor formats, if any?

Generate Font…
     otf, ttf, et. al. usable font formats
     web font formats

Export…
     eps
     other non-font graphic formats
     obsolete/legacy font formats?
     Maybe other font editor formats should go here, if any?


On Thu, May 7, 2015 at 1:16 PM, Andreas Larsen <notifications@github.com>
wrote:

> So Export = Export Font ?
>
> But ttf, otf, etc. are also formats
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fontforge/fontforge/issues/2257#issuecomment-100004646>
> .
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by andreaslarsen** [comment]
Problem is FontForge can't save as ufo - only export/generate (whatever word one prefers to use)

**Comment by pathumego** [comment]
@davelab6 I think `Export > UFO` should be added.. Even though it is a export, it is different from rest of the formats that `Generate Fonts` has (a source)

**Comment by davelab6** [comment]
Fine with me

**Comment by andreaslarsen** [comment]
@davelab6 @pathumego we have another issue for hotkeys but I'd say we add a page in the doc with hotkey issues we might encounter when we're fixing the menu. https://github.com/fontforge/fontforge/issues/2252

**Comment by andreaslarsen** [comment]
```
Export
  Graphic...
  Font...
  Mac Family...
  UFO...
  TTC...
```

**Comment by andreaslarsen** [comment]
@davelab6 my original questions wasn't as much about how the export menu should look but more about the general use of the submenu title within the submenu (which is currently highly inconsistent and I'd suggest we don't do it).
e.g.
```
Select
  Select All
```
becomes
```
Select
  All
```

**Comment by davelab6** [comment]
Order by frequency of use? Eg

Export >
Binary...
UFO...
Mac Family...
TTC...
Graphics...

**Comment by andreaslarsen** [comment]
Frequency is very user dependent so I'd rather we do a "thematic" order so there is some logic in the menu

**Comment by davelab6** [comment]
Is this order not thematic? :)

I agree about deduplicating sub menu strings

**Comment by andreaslarsen** [comment]
`Font` (why binary?), `Mac Family` and `TTC` are formats you can use as end user - `UFO` isn't :)

**Comment by davelab6** [comment]
Context :)

Export >
Font...        ((This is true of all but the last item, so i suggested
Binary, but I'm ok with this as is. and is surely the most common kind of
export, so belongs at top spot))
OpenType ((same as UFO, this is so common, worth it's own item))
UFO...     ((This is not needed strictly, but prior so use it do so
frequently enough it's worth having its own own... could even be a Save
item, and so thematically belongs next to font as it is the same as font
with a preset option))
Mac Family... (( font collection))
TTC... ((Font collection))
Graphics... ((Not a font, so last))

**Comment by andreaslarsen** [comment]
Ideally UFO should be in the save menu but since FF doesn't support I'd think it would confuse the user.
.ttc is to e.g. .ttf what .mpkg is to .pkg so I'd say font and the font collections are more "related" than font and a font source format but I don't really care:)

As long as long as we agree on ordering thematically then what one percepts as belonging together will always be debatable. 

The argument for having UFO as it's own item was more because it was the only one that was a source format wasn't it?

**Comment by davelab6** [comment]
Yes

> Ideally UFO should be in the save menu but since FF doesn't support I'd
think it would confuse the user.

I don't understand, we are driving the menus, if you think it belongs
there, let's put it there

**Comment by andreaslarsen** [comment]
But FF can't save UFO's like it can save e.g. sfdir can it?

I can't choose UFO as my source format and then just use cmd+s and be done with it. 

UFO should be in the save when FF can do that but until then it's more of an "export" that is happening.

**Comment by pathumego** [comment]
@andreaslarsen  Agree. I had this moment. Opening a UFO , do changes and hit ctr+s to save.

**Comment by andreaslarsen** [comment]
A couple of thoughts general thoughts. We are doing most of it already and have also discussed a lot of it but I figured there wasn't any harm in doing a recap.

**Roadmap**
- Draft of the new unified menu (what we are doing in gdoc now)
- List all changes needed to be done to get the menu looking like that
- Get @frank-trampe to implement those changes (assuming some of it is "easy" then tell us how to do it)
- Try the menu system out.
- Make adjustments (if needed)
- Draft tooltips for items that could benefit from such.
- Draft all right-click menus. 
  - We can continue doing this now but I think it's most important to get the menu working and right first.  
  - Right clicks are "nice-to-have" and it's easier to see which items should be there after you get accustomed to the new menu.
- Implement tooltips and right click menus.

**Principles behind the menu layout**
- The same menus for Font, Glyph and Metrics window
  - Not just top level but the entire menu
  - Obviously with difference in what is greyed out
- Short and descriptive names
  - Only plural when absolutely needed
  - Always "..." when the menu item presents the user with options before doing the action. 
  - Copy -> ~~Copy~~ References
- Submenu ~~-> submenu~~ -> item
- Try to order/group things thematically so the menu structure is as logical as possible

**Comment by pathumego** [comment]
Before the release / After release
- Announcement on forums + mailing lists (libregraphics lists)
- Blog posts (Libre graphics world, typedrawers, ubuntu sites)
- Update Documentation
- Update Screenshots on DWFF
- Update Website

**Comment by pathumego** [comment]
@lpsandaruwan

**Comment by larsenwork** [comment]
@pathumego sounds great there should be plenty of stuff to do in the doc based on the comments there. @lpsandaruwan please ask if you have any questions

**Comment by pathumego** [comment]
@larsenwork So I just had a chat with @lpsandaruwan. He will spend next 2-3 days getting to know the codebase properly. And he will post a small proposal on how he plan to implement this. Then we will see if @frank-trampe, and you can review it. Then go for it :) Meantime we have to think about how we plan on letting the users know about the upcoming changes.

**Comment by lpsandaruwan** [comment]
@davelab6  @larsenwork  @pathumego 
Hi, It's nice to meet you all.
I'm still studying FontForge code base. Like @pathumego said, I need some time to come up with a implementation proposal. And I need some clarifications on user interface. Currently I'm familiar only with QT and GTK frameworks. :) Thanks.

**Comment by larsenwork** [comment]
Sounds great @lpsandaruwan - maybe @frank-trampe or someone else could spend 5-10 minutes giving you a few pointers to get started - would be 5 minutes well spent :wink:

**Comment by frank-trampe** [comment]
As most of you probably know, FontForge has its own widget kit, in part, supposedly, because, in the early days of FontForge, no existing widget kit supported Unicode.

The widget kit is mostly in the gdraw directory. It took me a long time to come to a vague grasp of it, and, after several years of heavy work, I still can't always say off-hand what the best way is to do something. The one thing that I can do rather consistently is to explain why a proposed way of doing something is wrong. I can also identify good places to start looking for particular things.

Gdraw has constructor functions. FontForge builds a GGadgetData item and feeds it to the constructor. Widgets can have children, and it can be confusing to initialize all of the children incrementally. So, in order to shorten the required code and to improve organization, FontForge will instead build nested double-NULL-terminated arrays of the GGadgetCreateData type (which includes information about which type/constructor to use) and feed those to GGadgetsCreate. (See FontInfo for an extreme example of this approach.)

Menus follow the widget model also. One builds the menus with GMenuItem2 arrays (with nesting for nested menus).

These widget initialization types (GGadgetData, GGadgetCreateData, and GMenuItem2) are used only at initialization; live changes to a widget must go through the pointer (or pointer tree) returned from the constructor, and one can reuse the same GGadgetData struct for creating multiple widgets.

**Comment by pathumego** [comment]
@frank-trampe Thanks for this!

**Comment by larsenwork** [comment]
@pathumego Some general thoughts on some of the principles I think should be behind every change we make or don't make.

**1. Value**
It should make "life" better/easier for future user and/or future developer/maintainer. These will often conflict as the optimal solutions for the end user often requires more code. If you have a commercial product the end user is crucial but in an open source volunteer based project the catering for the programmers is just as important.

**2. Could this information be on the web**
We are almost always online anyway - little is lost but a lot can be gained. 
E.g. the license information used to be three places (5 if you count the copyright notice in the startup window + in the about window) but none of them were kept up to date. We are moving towards just having it [here](https://github.com/fontforge/fontforge/blob/master/LICENSE) and make the website and app point there.
Another example could be the OFL debacle I managed to start...a simple solution could be removing it from the app and instead make the button link to a webpage (could be a chapter in dwff) that had a short description of difference between licenses and a simple web form/license generator. This would be more valuable for the end user and easier to update. 

**3. Is there a OS standard we should+can follow**
E.g. the shift vs ctrl discussion (also my "fault"...). It was fairy easy to follow the OS standard for both win + mac (can remember if the solution has been implemented just yet though) so we chose to do so.
Another example could be the about window: On mac it's almost always top left menu bar with the same name as app and then first menu item. FontForge doesn't have a menubar (X11 has) and doesn't have a menu with app name (because win users). The only critical information in about windows is the version number which is why I suggested we'd remove the about window (and startup window) and just display the version number directly in the menu.

TL'DR: Move what can be moved to the web and focus on improving core app function in a easy maintainable way.

**Comment by lpsandaruwan** [comment]
Thanks to @frank-trampe  , after hours of digging I figured out, the menu structure is in the fontforgeexe/fontview.c file. Need some time to restructure it. :)

**Comment by lpsandaruwan** [comment]
The functions and structures which creates menus and menu items are in gdraw/gmenu.c file. I can edit the current menu structure in fontforgeexe/fontview.c file slightly studying gdraw's gmenu.
@davelab6  Can you give me permission to open new branch here ?

**Comment by pathumego** [comment]
@lpsandaruwan Go ahead :) you should have necessary permissions I think.

**Comment by jtanx** [comment]
Something to clarify: 

> Browse web (broken)

Are you talking about removing the code related to direct FTP/HTTP support? If so, I'm all for it...

**Comment by pathumego** [comment]
@jtanx Its the `Browse Web` option on `File Menu` It is broken and crashes. I don't know what chunk of code we are removing. Suggestions?

**Comment by jtanx** [comment]
@pathumego, it's already been dropped since #1533. The latest builds no longer have that feature at all.

**Comment by pathumego** [comment]
@jtanx Its still available on OSx builds :/ 

Anyway you meant the same this with `code related to direct FTP/HTTP support? If so, I'm all for it...` ?

**Comment by jtanx** [comment]
Strange - I certainly don't see it on Windows nor on a recent Linux build. Certainly [this part](https://github.com/fontforge/fontforge/pull/1533/files#diff-37e732ae60bea33ca0254b374d14b9d1L4376) suggests it has been removed. 

This is what I see on Windows:
![Uploading oepn.PNG…]()

> Anyway you meant the same this with code related to direct FTP/HTTP support? If so, I'm all for it... ? 

I was referring to the general HTTP/FTP code that FontForge has lying around (apparently FontForge can directly browse FTP sites, but not on Windows), so I guess what you're talking about is not exactly the same as what I'm thinking about.

**Comment by pathumego** [comment]
@jtanx Yep seems we are talking about two different things. I filed an issue, #2307.

**Comment by lpsandaruwan** [comment]
@larsenwork  @pathumego  Because of that I'm not that much familiar with the FontForge, It is better if I can get a detailed docs about new menu structure for all three windows, like inactive options, moving from this to this, etc. :-)

![ff_edit_menu](https://cloud.githubusercontent.com/assets/5220773/8018397/a1459018-0c37-11e5-8cef-a9ac9aafa08b.png)

**Comment by larsenwork** [comment]
@lpsandaruwan sure - I don't know how much time I have this weekend but I'll try. I'm not sure what information you want about inactve options because I don't think we are making any changes in when elements should be greyed out - just moving things around.

**Comment by lpsandaruwan** [comment]
@larsenwork  Thank you. :-)

**Comment by lpsandaruwan** [comment]
Sometimes I get lost, whether it is from another menu from the same window's another menu or it is from another window's same menu. Because of three main views are using three different files to draw the interface, if we want to use the same menu structure for all three views, it is good to have an idea about inactive options and other details. :-)

**Comment by larsenwork** [comment]
ok, you may already know this but the general rule you can follow is if something wasn't shown in e.g. metrics window before it probably should be inactive when you add it to the metrics window.

**Comment by larsenwork** [comment]
do you have the top level in place: 
```
File
Edit
Font
Glyph
Path
Point
Metrics
Extensions
View
Window
Help
```

**Comment by pathumego** [comment]
@lpsandaruwan ok I think i can spend some time over the weekend completing this https://docs.google.com/spreadsheets/d/1jGKa63CDv8SbNjnARMpOPZBsSLRtQT2jEmwk6z7e27o/edit#gid=0 

But I need you to review it and tell me what info you exactly need. If you could arrange the columns and rows with labels of info you need I can fill it out. Since then ping me or @larsenwork for immediate clarifications.

**Comment by lpsandaruwan** [comment]
@larsenwork  @pathumego  great!!!

**Comment by pathumego** [comment]
Since all the discussed things have been documented and moved to either issues/milestones or Docs closing this. The issue specific discussions should be on respective issue page. :)
