### ISSUE TITLE
Mac Quality-of-life improvements

### ISSUE THREAD

**Issue by MaddTheSane** [fontforge/fontforge#3463]
This is a general issue on ways to make FontForge a better Mac citizen:

- [ ] More entries in the info.plist file [#3438].
- [ ] Make it relocatable/launchable from anywhere on the file system [#2957].
- [ ] Better Finder integration [#2042].
- [ ] Use the native Mac menu bar instead of our own.
- [ ] Use native open/save dialogs.

**Comment by ctrlcctrlv** [comment]
I doubt #2957 is easily fixable, and the Mac menu bar one would require big changes to gdraw. Is there any reason you made a meta-issue rather than just new issues for №4 and №5?

**Comment by MaddTheSane** [comment]
I just put what I felt it would be a good idea to group these issues together. If you feel like the fourth and fifth would be better represented as separate issues, I can create separate issues.

**Comment by jtanx** [comment]
For #2597, do the [CI builds](https://dl.bintray.com/fontforge/fontforge/) work at all? They should be relocatable (by fixing up the import paths), but I don't have a proper system to actually test anything Mac on.

**Comment by skef** [comment]
I may be in a position to take a look at #2957 in the nearish future (borrowing a machine). And I coincidentally have some experience with MacOS application bundles and "wrappers". However, just looking at the dmg doesn't reveal (or I haven't been able to determine) the relationship between the FontForge python shared object and the system. 

Is a MacOS X user supposed to be able to run a python script with "import fontforge" at the top? And if so, how does that work in relation to the application bundle?

**Comment by ctrlcctrlv** [comment]
> Is a MacOS X user supposed to be able to run a python script with "import fontforge" at the top? And if so, how does that work in relation to the application bundle?

It doesn't, unless they set their `PYTHONPATH` to the correct location inside the bundle. Many people install FontForge to use the scripting functionality, or for it to be used by other applications, so I think if we make it relocatable we're going to break many people's expectations if they update.

**Comment by skef** [comment]
Even if there was a standard or project-supplied means of setting the `PYTHONPATH` relative to the system `Applications` directory, I don't see how making the bundle relocatable would hurt. That means would just be a reason to put it in that location *when possible*. As it is, it sounds like people have their own means of setting the path, when they do, and can therefore set it how they like.

**Comment by snakebyte69** [comment]
> > Is a MacOS X user supposed to be able to run a python script with "import fontforge" at the top? And if so, how does that work in relation to the application bundle?
> 
> It doesn't, unless they set their `PYTHONPATH` to the correct location inside the bundle. Many people install FontForge to use the scripting functionality, or for it to be used by other applications, so I think if we make it relocatable we're going to break many people's expectations if they update.

How is this configured?
