### ISSUE TITLE
Release Meta-Issue

### ISSUE THREAD

**Issue by skef** [fontforge/fontforge#3499]
The date of the next release of FontForge has been slipping, most likely due to people's personal schedules. I am starting this issue to list things that *I* am aware of that *may* cause trouble in trying to do a new release, so that those things might get some attention from people who have some time. I encourage anyone else to edit this issue description to add new items, link up to other issues as they are filed, and so on. 

- [ ] Doc Synchronization: As changes are made to the interface people generally update the `.html` files in `doc`. However, there is no current route from there to the website, which is where most people will look. How should the website get updated, and what should the doc system be going forward? 
- [ ] Verify and change `--enable` and `--disable` `configure` flags: FontForge now supports an alternate GDK graphics layer. Other facilities suffer from bit-rot. Ideally, `configure` run with no arguments on a given architecture (linux, Mac, Windows, etc.) would choose the features most appropriate to that architecture. That way distros are more likely to get a better feature set. Are the flags currently arranged this way? What features does the project think should be consistently available? Who should be using GDK? 
- [ ] Update build instructions: The various in-repo documents include installation instructions from multiple eras. Most of that is what source control history is for. How does one build the software for each architecture? What are the dependencies? Even if some builds are too complicated for non-experts, ideally the information would be available in some other form besides a travis script somewhere.

**Comment by TotoCoelo** [comment]
I recently managed to compile fontforge on windows 10. I know how to compile and install software on linux, but the situation on windows 10 is a bit different. There are some things that are not mentioned in the documentation ([https://github.com/fontforge/fontforge/blob/master/INSTALL-git.md](url)).

First of all I choose MSYS2 as the building platform. As I was not familiar with MSYS2 it did not work right away. It turned out that I had to start MSYS2 with it's `mingw64` subsystem enabled.
After installing the necessary packages (from the `msys2` subsystem) I was able to build fontforge. When I tried to run it, there was no gui. After inspecting the configure output it turned out that it needed either xwindows of gdk. So I ran `./configure --enable-gdk=gdk2`
This enabled me to compile fontforge succesfully and I was able to run it with a gui. I did not test this fontforge build extensively, but I was able to load a font that I created with the previous release of fontforge.

I hope this is of any help? If you need more details please ask.

**Comment by skef** [comment]
It's good confirmation, and will likely help with the docs.

Most of the existing pointers to FontForge packages for windows point to complex and seemingly out of date external packaging. But it sounds like enough has been integrated into the repository to build with `configure` (assuming the relevant tools are available). 

GTK3 seems to be available for MSYS2. Did you choose GDK2 explicitly or was a default (for something)?

**Comment by bagong** [comment]
I tried to follow the build instruction - following the linux instructions using msys2. after running ./bootstrap (in the mingw64 mintty running as admin) I got to the point below. Any hints?

...
Creating m4/gnulib-cache.m4
Finished.

You may need to add #include directives for the following .h files.
  #include <arpa/inet.h>
  #include <locale.h>
  #include <stdio.h>
  #include <string.h>
  #include <strings.h>
  #include <unistd.h>
  #include "c-strtod.h"
  #include "progname.h"
  #include "xalloc.h"
  #include "xvasprintf.h"
  #if HAVE_ICONV
  # include <iconv.h>
  #endif

You may need to use the following Makefile variables when linking.
Use them in <program>_LDADD when linking a program, or
in <library>_a_LDFLAGS or <library>_la_LDFLAGS when linking a library.
  $(GETHOSTNAME_LIB)
  $(INET_NTOP_LIB)
  $(LIBSOCKET)
  $(LTLIBICONV) when linking with libtool, $(LIBICONV) otherwise
  $(LTLIBINTL) when linking with libtool, $(LIBINTL) otherwise

Don't forget to
  - add "lib/Makefile" to AC_CONFIG_FILES in ./configure.ac,
  - mention "lib" in SUBDIRS in Makefile.am,
  - mention "-I m4" in ACLOCAL_AMFLAGS in Makefile.am,
  - mention "m4/gnulib-cache.m4" in EXTRA_DIST in Makefile.am,
  - invoke gl_EARLY in ./configure.ac, right after AC_PROG_CC_C99,
  - invoke gl_INIT in ./configure.ac.
Copying file compile
Copying file depcomp
bootstrap: running: autoreconf --symlink --force --install
' is already registered with AC_CONFIG_FILES.
../../lib/autoconf/status.m4:288: AC_CONFIG_FILES is expanded from...
configure.ac:793: the top level
autom4te: m4 failed with exit status: 1
aclocal-1.16: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

**Comment by jtanx** [comment]
You can follow what's done in https://github.com/fontforge/fontforge/blob/master/.appveyor.yml for windows builds. It's basically just call ffbuild.sh from https://github.com/jtanx/fontforgebuilds

As for GDK2 vs GDK3, go with GDK3. I'm tempted to rip out the GDK2 support.

**Comment by skef** [comment]
@jtanx did you ever wind up looking into a Visual Studio build, for python compatibility?

**Comment by jtanx** [comment]
Yeah, a VS build is highly unlikely. The dependency on gnulib basically ties FontForge to autotools, and FontForge itself won't compile cleanly without it.

It'd be nice if FontForge could not be dependent on it, then we could actually use something like cmake or meson, but that's more of a pipe dream.

**Comment by TotoCoelo** [comment]
@skef If it is still relevant, `./configure --enable-gdk=gdk3` does also work.

@bagong Did you install `mingw-w64-x86_64-pkg-config`? `./bootsrap` requires this as well.

**Comment by bagong** [comment]
@TotoCoelo yes, I did, thank you. I'll have a look at that build script. But I must admit I am a bit overwhelmed by it's complexity ;)

**Comment by jtanx** [comment]
Alright, I'll cut the release. Tag anything that's wanted in this into https://github.com/fontforge/fontforge/projects/2

Target is to cut by tomorrow, but that's dependent on how outstanding prs/issues are dealt with.

On docs: For this release, no change, but feel free to standardise this. If the structure's the same, maybe diff what's in the repo vs the website and update accordingly.

On changing compiler flags: Again, not for this release, gdk is still (imo) somewhat experimental. I'd rather keep it explicitly enabled instead of defaulting to it on some OSes. I'd also recommend sticking to using the x11 backend for linux, the windows and mac builds will be the gdk. Although the mac build may still end up being x11, because iirc there's some strange behaviour with gdk on startup

On build instructions, again, this is a documentation thing, but I'm not calling this a blocker to release either.

**Comment by frank-trampe** [comment]
@jtanx, I understand that we need to get a release out, and I'm happy to do so when you feel it's appropriate, but let me do the actual tag notes and announcements. Are you able to build a distributable Macintosh package, by the way? I'm out of town and can't do so until late next week.

**Comment by jtanx** [comment]
Yes, I can sort something out with the Mac bundle. Given that I'm in a position to cut the release, I don't see why I should have to wait, cutting a release shouldn't be this hard.

**Comment by skef** [comment]
The windows package (at least) needs to communicate what we've been talking about in #3501: where to put init scripts, as opposed to standard python packages.

**Comment by jtanx** [comment]
The location won't have changed from last time (and hasn't changed for years); the installer doesn't set the `FF_PORTABLE` flag, but I guess docs could be improved nonetheless

**Comment by jtanx** [comment]
Looking at cutting by today was too ambitious, Let's hold off on that until the 16th (next Saturday). That might work out better for everyone anyway. I'll look to get it into a releasable state by then.

**Comment by skef** [comment]
> The location won't have changed from last time (and hasn't changed for years); the installer doesn't set the `FF_PORTABLE` flag, but I guess docs could be improved nonetheless

In that case it depends on how many people are going to be grabbing our incremental Windows builds.

**Comment by ctrlcctrlv** [comment]
Regarding the Windows build, I receive:

```
      0 [main] sh 25064 fork: child -1 - forked process 24564 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
gnulib/gnulib-tool: fork: retry: Resource temporarily unavailable
      1 [main] sh 25212 fork: child -1 - forked process 24564 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
gnulib/gnulib-tool: fork: retry: Resource temporarily unavailable
```

using MSYS2 MinGW64 64-bit

**Comment by ctrlcctrlv** [comment]
Hmm...despite that it still let me run `./configure --enable-gdk=gtk3`...I did need to install `pkg-config` and `patch` via the built-in MSYS2 pacman. Doing `pacman -S mingw-w64-x86_64-gtk3` now, will be shocked if it really works !

**Comment by jtanx** [comment]
I can't see why it wouldn't, I build all the FF stuff with msys2. Although that option should be `--enable-gdk=gdk3`, it might be defaulting to gdk2 with `gtk3` as the option.

Not sure about those fork calls, did you just install msys2 (or do a `-Syuu`)? If so, you need to quit everything before using it again

**Comment by ctrlcctrlv** [comment]
Hit another brick wall: 

https://github.com/fontforge/fontforge/issues/2283#issuecomment-472264271

**Comment by jtanx** [comment]
Alright, just waiting on #3538 and #3542 to finish building (not critical, but might as well). Final tag is going to be 20190317. Once everything's in place, I'll tag and do the builds, and upload them to a staging release. I'll leave it up to @frank-trampe to do the announcements.

**Comment by skef** [comment]
Sounds good! I was hoping to coalesce the doc changes before now, but realistically we have a day or two before that could matter anyway.

**Comment by jtanx** [comment]
Alright, it's tagged, looking at getting those builds added to https://github.com/fontforge/fontforge/releases/tag/20190317 soon.
